version: "3.7"
services:
  db:
    image: postgres:15
    container_name: db_app
    command: -p 5435
    expose:
      - 5435
    env_file:
      - .env-prod

  redis:
    image: redis:7
    container_name: redis_app
    command: --port 5436
    expose:
      - 5436

  app:
    build:
      context: .
    env_file:
      - .env-prod
    container_name: fastapi_app
    command: ["/fastapi_app/docker/app.sh"]
    ports:
      - 9999:8000
    depends_on:
      - db
      - redis

  celery:
    build:
      context: .
    env_file:
      - .env-prod
    container_name: celery_app
    command: ["/fastapi_app/docker/celery.sh", "celery"]
#    environment:
#      - CELERY_BROKER=redis://redis:5436/0
#      - CELERY_RESULT_BACKEND=redis://redis:5436/0
    depends_on:
      - redis

  flower:
    build:
      context: .
    env_file:
      - .env-prod
    container_name: flower_app
    command: ["/fastapi_app/docker/celery.sh", "flower"]
    depends_on:
      - redis
      - celery
    ports:
      - 8888:5555
